# Generated by Django 5.0.6 on 2024-05-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_delete_datasiswa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
